services:

  mongo:
    container_name: mongod
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: sample
    command: mongod --auth
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-hono:
    container_name: hono
    build:
      context: .
      dockerfile: ./Docker/Hono/Dockerfile
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./Hono:/app
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo/sample
      ME_CONFIG_BASICAUTH: false
    command: npm run dev

  vuejs:
    container_name: vuejs
    build:
      dockerfile: ./Docker/Vite/Dockerfile
    ports:
      - 5173:5173
    command: tail -f /dev/null # Once installed, replace by `sh -c "npm install && npm run format && npm run dev"`
    volumes:
      - ./Vite:/var/www/app
    environment:
      - API_URL=hono:3000
      - API_TOKEN=e084db95-30d3-43fa-814d-f93eb2e0978a # Higly recommend to create a secret token
